### ISSUE TITLE
Where do I change the parallel light processing setting of the mode for scalable lux?

### ISSUE THREAD

**Issue by ghost** [RelativityMC/ScalableLux#8]
Where do I change the parallel light processing setting of the mode for scalable lux?

**Comment by ishland** [comment]
If you are using C2ME, the parallel lighting feature is always enabled and the thread count is controlled by C2ME instead.

If you aren't, it is controlled by the `parallelism` setting in the `config/scalablelux.properties`. It sets the thread count. 
Any non-positive value means auto, and setting it to `1` means disabled, and setting it to `2` or more means enabled.
